/**
 * Represents a report generated by the user at some point in time
 * This model serves as a handle on a persisted report that can be downloaded,
 * or report request that can be reissued to regenerate a historic report for download again
 */
export class Report {

  public id: number;
  public label: string;
  public status: string;
  public created: Date;

}
