/**
 * Represents a report generated by the user at some point in time
 * This model serves as a handle on a persisted report that can be downloaded,
 * or report request that can be reissued to regenerate a historic report for download again
 */
import { AssessmentType } from "../shared/enum/assessment-type.enum";

export class Report {

  public id: number;
  public label: string;
  public status: string;
  public reportType: string;
  public assessmentType: AssessmentType;
  public subjectId: number;
  public schoolYear: number;
  public created: Date;

  public get completed(): boolean {
    return this.status === 'COMPLETED';
  }

  public get processing(): boolean {
    return this.status === 'PENDING' || this.status === 'RUNNING';
  }

  public get regenerable(): boolean {
    return !(this.completed || this.processing);
  }

  public get statusColor(): string {
    if (this.completed) {
      return 'blue-dark';
    }
    if (this.processing) {
      return 'aqua';
    }
    return 'maroon';
  }

}
